### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by elisechant** [Thinkmill/design-system#6]
Are contributions open? if so, how do we contribute? Is there a committee? 

To make this clear, why not add a contributions.md and state where you are or are not accepting contributions at this stage, and/or how else we could get involved (Thinkmill vs public), ie there is a committee, Slack group or what-not else?

**Comment by gwyneplaine** [comment]
Thanks @elisechant , a contributions.md is a great idea, as well as a CoC 👍, we'll work on getting that in as soon as we can. 

In the meantime, please feel free to discuss or call out this work in the #design-systems channel on slack, this will also be the focus of DSC (every Friday, 12:30 - 1:30; remote-friendly) going forward as well, so if you have the time and would like to participate, let me know and I'll add you to the calendar invite
