### ISSUE TITLE
Incorporate Emma Wedekind's Component Checklist

### ISSUE THREAD

**Issue by jesstelford** [Thinkmill/design-system#7]
https://twitter.com/EmmaWedekind/status/1177248937763311617?s=20

![https://pbs.twimg.com/media/EFZtqrsWwAMingw?format=jpg&name=large](https://pbs.twimg.com/media/EFZtqrsWwAMingw?format=jpg&name=large)

**Comment by gwyneplaine** [comment]
This is great, thank you @jesstelford , and @elisechant for picking this up from slack

**Comment by gwyneplaine** [comment]
Added this image to the existing README,  in [the following commit](https://github.com/Thinkmill/design-system/commit/bd15f67cd28e6b165eac0ad170df8d6f13fadef1)

will iterate on this as we refine our thinking around what we think best practice definition of done should look like, thanks again @jesstelford  :D
